{
  "hash": "b2bfe284311e689e3bd7c548155e875e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ncategories: \"Lab 8\"\ntitle: \"Lab 8: Inference for difference in two Means\"\nexecute:\n  eval: true\nformat:\n  html: \n    code-link: true #Supposed to create a link to documentation but its not, for some reason.\n    code-block-border-left: \"#31BAE9\"\n    code-fold: show #also try true OR false and decide if you like it.\n    code-tools: false\n    code-copy: true\n---\n\n\n\n\n\n\n## [Introduction]{style=\"color:#4166f5;\"}\n\nIn this lab, we consider statistical inference for the difference in two independent means. Scenarios that fall under this category include those where we are interested in learning about the average value of a numerical variable for **two different** groups. For example, we may be interested in learning about the average weight loss for individuals who participated in a weight loss program with financial incentives versus those who participated without financial incentives. In such scenarios, the parameter of interest is the difference in population means (denoted by $\\mu_1 - \\mu_2$) and the statistic we use to estimate it is the difference in sample means (denoted by $\\bar{x}_1 - \\bar{x}_2$).\n\n## [Creating your Quarto File]{style=\"color:#4166f5;\"}\n\nGo to posit cloud (<https://posit.cloud>) and open the MATH 144 project. Once your MATH 144 project is open, clean up the console and the environment. Close any open documents and datasets that you don't need.\n\nNext, create your new quarto file as follows:\n\n-   File \\> New File \\> Quarto document. Use the file name `Lab_8`. Do not delete the `.qmd` extension.\n\n-   Add the `author` and `title` keys to the `YAML` section. Write your name (in quotes) in the author field and set the title to `Inferene for two Independent Means`.\n\n-   Change the output option to `pdf` then click on `render`. A PDF document with your name and title should pop up. If the popup blocker shows up, click try again.\n\n## [Context & Scenario]{style=\"color:#4166f5;\"}\n\nA group of researchers wanted to investigate whether financial incentives help individuals lose weight. They recruited 38 individuals who wanted to lose weight and randomly assigned them to either a **incentive group** (given financial incentives) or a **control group** (not given any financial incentives). After 4 months, the researchers recorded the amount of weight lost **(before - after)** by each individual. Three months after the initial 4 months, they also recorded the weight lost by each individual again to see if the weight loss was maintained. The data set is saved as `WeightLossIncentive` and is available in the `Stat2Data` package. Because this is a new package, you need to install it first.\n\n***DO NOT*** run the package installation in a code chunk because the installation will repeat every time you render. Use the console or install packages in the packages section next to files.\n\n## [Packages and Data]{style=\"color:#4166f5;\"}\n\nCreate a code chunk and load the following packages and data:\n\n``` toml\n#| include: false\nlibrary(Stat2Data)\nlibrary(tidyverse)\nlibrary(infer)\ndata(WeightLossIncentive)\n```\n\nAfter running the above code chunk, the `WeightLossIncentive` data set should appear in the environment area. Open it and examine the cases and variables. You should see the following variables:\n\n`WeightLoss`: Weight lost 4 months into the program. A negative number means weight gain.\n\n`Month7Loss`: weight lost 3 months after the initial 4 months. A negative number means weight gain.\n\n`Group`: Whether someone was given financial incentive (treatment) or not (control).\n\n## [Research Question and Hypotheses]{style=\"color:#4166f5;\"}\n\nWe want to answer the following research question via statistical inference:\n\n***Research Question:*** Four months into the program, would individuals who receive financial incentives lose more weight on average than those who don't receive the incentives?\n\n***Null Hypothesis:*** There is *no difference* in *average* weight loss between individuals in the treatment group and those in the control group.\n\n$$H_0: \\mu_{I} = \\mu_{C}.$$\n\n***Alternative Hypothesis:*** Individuals who receive financial incentives (treatment) would lose more weight on average than those who don't.\\\n$$H_a: \\mu_{I} > \\mu_{C}.$$\n\n***Note:*** To answer this question, we will use the variables `WeightLoss` (numerical) and `Group` (categorical) from the `WeightLossIncentive` dataset.\n\n## [Exploring Data via Visualization]{style=\"color:#4166f5;\"}\n\nLet us start by visualizing the distribution of the `WeightLoss` variable using a box plots. Since we have two groups, it would be good to have **side-by-side** box plots (on the same scale) to allow comparison. See below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWeightLossIncentive |>\n  ggplot(aes(x = Group, y = WeightLoss, fill = Group)) +\n  geom_boxplot() +\n  labs(title = \"Boxplot of Weight Loss by Group\",\n       x = \"Group\",\n       y = \"Weight Lost after 4 months (pounds)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab_8_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\nThe side-by-side box plots above shows that individuals in the incentive group lost more weight on average than those in the control group. The median weight loss for the incentive group appears to be higher than that of the control group. There are no apparent outliers in either group. The interquartile range (IQR) for the incentive group seems to be larger than that of the control group, indicating more variability in weight loss among individuals who received financial incentives.\n\n## [Observed Statistic]{style=\"color:#4166f5;\"}\n\nThe observed statistic in this scenario would be the difference in average weight lost between the incentive and the control group. The code below drops the missing values from the `WightLoss` variable, then groups by Group and calculate the mean for each group:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWeightLossIncentive |>\n  drop_na(WeightLoss) |>\n  group_by(Group) |>\n  summarize(mean(WeightLoss))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Group     `mean(WeightLoss)`\n  <fct>                  <dbl>\n1 Control                 3.92\n2 Incentive              15.7 \n```\n\n\n:::\n:::\n\n\n\n\nThe observed statistic is:\n\n$$\\text{Observed Statistic} = 15.68 - 3.92 = 11.76 \\text{ pounds}.$$\n\n## [Running Simulations]{style=\"color:#4166f5;\"}\n\nNext, we want to run simulations to generate the null distribution.  We will use the `infer` package functions to do this. See the code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12) # Prevents simulated data from changing.\nnull_distribution <- WeightLossIncentive |>\n  specify(WeightLoss ~ Group) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  calculate(stat = \"diff in means\", order = c(\"Incentive\", \"Control\"))\n```\n:::\n\n\n\n\nUpon running the code the `null_distribution` object should appear under the environment area. This contains 1000 simulated difference in means under the assumption that the null hypothesis is true(hence centered around 0).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_distribution |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(binwidth = 2, fill = \"#4963D4\", color = \"white\")+\n  geom_vline(xintercept = 11.76, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](lab_8_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# The bars are filled using the color code \"#4963D4\". Google html color codes.\n```\n:::\n\n\n\n\nThe vertical line to the right represents the **observed statistic**(11.76 pounds) calculated earlier.\n\n## [P-value Calculation]{style=\"color:#4166f5;\"}\n\nThe P-value is calculated by estimating the amount of differences at least as extreme as the observed statistic and dividing by the total number of simulated differences, i.e., 1000. From the above histogram, we can see that there are no values that are greater than or equal to the observed statistic (the vertical line), so the P-value would be close to 0.\n\nWe use a function called `get_p_value()` from the `infer` package to calculate the P-value. See below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_distribution |>\n  get_p_value(obs_stat =11.76 , direction = \"right\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       0\n```\n\n\n:::\n:::\n\n\n\n\nThis P-value is the probability of observing a difference in means as extreme as 11.76 pounds (or more) by chance alone if the null hypothesis were true.\n\n## [Interpretation & Conclusion]{style=\"color:#4166f5;\"}\n\nThe p-value is small (less than 0.05) which means we **reject** the null hypothesis. Therefore, the data provides strong evidence that financial incentives likely result in more weight loss after 4 months.\n\n## [Confidence Interval]{style=\"color:#4166f5;\"}\n\nNext, we want to create a confidence interval to estimate the true difference in average 4-month weight loss between the two groups. First, we run a bootstrap simulation from the sample. You may want to review the class activities for week 11(Mon and Wed) if you need to refresh your mind on the physical mechanics of this process. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # Prevents simulated data from changing.\nbootstrap_dist <- WeightLossIncentive |>\n  specify(WeightLoss ~ Group) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"diff in means\", order = c(\"Incentive\", \"Control\"))\n```\n:::\n\n\n\n\nThe above code runs 1000 simulations of the difference in means using bootstrap resampling. Since we are resampling from the observed data, the bootstrap distribution will be centered around the observed statistic of 11.76 pounds. We can create a histogram to verify this. Examine then run the code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_dist |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(binwidth = 1.6,fill=\"darkgreen\", color=\"black\")\n```\n\n::: {.cell-output-display}\n![](lab_8_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Here, the bars are filled using \"darkgreen\".\n```\n:::\n\n\n\n\nNext, we use the `get_ci()` function from the `infer` package to find the 95% confidence interval:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_dist |>\n  get_ci(level = 0.95, type = \"percentile\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1     5.75     17.4\n```\n\n\n:::\n:::\n\n\n\n\nThe lower and upper bounds of the confidence interval are approximately 5.75 and 17.38 pounds, respectively.\n\n## [Interpretation of Confidence Interval]{style=\"color:#4166f5;\"}\n\nThis means we are 95% confident that the true difference in average 4-month weight loss between the incentive group and the control group is between 5.75 and 17.38 pounds. This interval does not include 0, meaning 0 is not a plausible value. Therefore, the interval supports the conclusion reached under the hypothesis test (we rejected the null hypothesis).\n\n## [Exercises]{style=\"color:#4166f5;\"}\n\nIn this lab exercises, you will use the same dataset (`WeightLossIncentive`) used in the explorations above. \n\nThe variable `Month7Loss` lists the weights of the participants 3 months after the initial 4 months. During this time, the financial incentives were withdrawn for both groups. <br> We want to perform statistical inference to check whether the weight lost between the two groups are still different at this time point. <br>\nIf we find that the groups are not different after the seventh month, then this is more evidence to suggest that it is indeed the financial incentives that lead to the weight loss. \n\n1.  **(1 pts)** State the null and alternative hypotheses to answer the research question: *Three months after the initial 4 months, would individuals who received financial incentives still lose more weight on average than those who didn't receive the incentives?*\n\n2.  **(1 pts)** Create side-by-side box plots to visualize the distribution of `Month7Loss` for the two groups. Briefly describe what you see in the box plots.\n\n3.  **(1 pts)** Calculate the relevant observed statistic.\n\n4.  **(2 pts)** Use the `infer` package to run simulations to create the null distribution of the observed statistic under the null hypothesis. Create a histogram of the null distribution and add a vertical line to represent the observed statistic. Why is the distribution centered around 0? Does the location of the observed statistic (the vertical line) suggest a large or small P-value?\n\n5.  **(2 pts)** Use the `get_p_value()` function to calculate the P-value for the hypothesis test. Based on the P-value, what is your conclusion regarding the research question? Use a discernibility level of 0.05 (5%) and make sure to write your conclusion in context. What do these results imply about the effectiveness of financial incentives on weight loss? You may want to compare your conclusion here with that from the exploration section above before incentives were withdrawn.\n\n6.  **(3 pts)** Use the `infer` package functions to generate a 95% confidence interval for the true difference in average weight lost between the two groups using the `Month7Loss` variable. Based on this interval, what can you conclude about the true difference in average weight lost between the two groups 3 months after the initial 4 months? Does this conclusion align with that from the hypothesis test results from #5 above? Explain.\n",
    "supporting": [
      "lab_8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}