{
  "hash": "2ef083fea47311313db2d5ad8c5c2076",
  "result": {
    "engine": "knitr",
    "markdown": "---\ncategories: \"Lab 9\"\ntitle: \"Lab 9: Inference for a Single Mean\"\nexecute:\n  eval: true\nformat:\n  html: \n    code-link: true #Supposed to create a link to documentation but its not, for some reason.\n    code-block-border-left: \"#31BAE9\"\n    code-fold: show #also try true OR false and decide if you like it.\n    code-tools: false\n    code-copy: true\n---\n\n\n\n\n\n\n## [Introduction]{style=\"color:#4166f5;\"}\n\nIn this lab, we consider statistical inference for a single mean. Scenario that fall under this category include those where we are interested in learning about the average value of a numerical variable for a population.\n\n\n## [Creating your Quarto File]{style=\"color:#4166f5;\"}\n\nGo to posit cloud (<https://posit.cloud>) and open the MATH 144 project. Once your MATH 144 project is open, clean up the console and the environment. Close any open documents and datasets that you don't need.\n\nNext, create your new quarto file as follows:\n\n-   File \\> New File \\> Quarto document. Use the file name `Lab_9`. Do not delete the `.qmd` extension.\n\n-   Add the `author` and `title` keys to the `YAML` section. Write your name (in quotes) in the author field and set the title to `Inference for a Single Mean`.\n\n-   Change the output option to `pdf` then click on `render`. A PDF document with your name and title should pop up. If the popup blocker shows up, click try again.\n\n## [Context & Scenario]{style=\"color:#4166f5;\"}\n\nAwesome Auto Car Company (AACC) is a big auto sales company with several franchises. AACC claims that the average sale price of cars at one of its franchises is \\$20,000. A small company is considering acquiring the franchise and wants an independent evaluation of this claim before moving forward.\nYou are hired as a consultant to assess the claim using statistical inference. As a first step, you collect a random sample of five cars from the franchise and record their sale prices (in US dollars), as shown below:\n\n$$18300, 20100, 9600, 10700, 27000$$\n\n## [Packages and Data]{style=\"color:#4166f5;\"}\n\nLoad the `tidyverse` and `infer` packages:\n\n``` toml\nlibrary(tidyverse)\nlibrary(infer)\n```\nWe will not pull the data from an external source. Instead, we will create the dataset using the `tibble()` function as shown below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales_data <- tibble(price = c(18300, 20100,\n9600, 10700, 27000))\n```\n:::\n\n\n\n\nAfter running the code, a new object named sales_data will pop up in your environment. Click on it to open it and examine the cases and variables. This is the data we will use.\n\n\n## [Research Question and Hypotheses]{style=\"color:#4166f5;\"}\n\nWe want to answer the following two research question via statistical inference:\n\n***Research Question 1:*** Is there enough evidence to suggest that the average car sale price at the said franchise is different (less than) from \\$20,000?\n\n***Null Hypothesis:*** The average car sale price is not different from\\$20,000.\n$$H_0: \\mu = 20,0000.$$\\\n***Alternative Hypothesis:*** The average car sale price is less than \\$20,000.\n$$H_a: \\mu \\neq 20,000.$$\n\n***Note:*** To answer this research question, we will use the `price` variable from the sales_data we created.\n\n## [Exploring Data via Visualization]{style=\"color:#4166f5;\"}\n\nIt is a common practice to run various summary statistics and create visualizations to explore the data before running inference. We have done data visualization in previous labs but here we will just make a box plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales_data |>\n  ggplot(aes(x = price)) +\n  geom_boxplot() +\n  labs(title = \"Boxplot for Sale Price\",\n       y = \"Sale Price in $\")\n```\n\n::: {.cell-output-display}\n![](lab_9_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\nDescribe the distribution of the `price` variable based on the boxplot above. Are there any outliers? What is the median sale price? What is the estimated interquartile range (IQR)?\n\n## [Observed Statistic]{style=\"color:#4166f5;\"}\n\nThe ***observed statistic*** is the average (mean) sale price based on the sample. We can calculate it using the code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales_data |>\n  summarize(average = mean(price))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  average\n    <dbl>\n1   17140\n```\n\n\n:::\n:::\n\n\n\n\n\n## [Running Simulations]{style=\"color:#4166f5;\"}\n\nNext, we want to run simulations to see the distribution of the observed statistic under the assumption that the null hypothesis is true. We will use the `infer` package to do this. Examine the code below before running it.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # Prevents simulated data from changing.\nnull_distribution <- sales_data |>\n  specify(response = price) |>\n  hypothesize(null = \"point\", mu = 20000) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"mean\")\n```\n:::\n\n\n\n\nA new object named `null_distribution` should appear in the environment area. This it contains 1000 simulated means. We can visualize the **null distribution** using a histogram and also indicate the location of observed statistic. See code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_distribution |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(binwidth = 1500, fill = \"#4963D4\", color = \"white\") +\n  geom_vline(xintercept = 17140, color = \"red\") +\n  labs(title = \"Histogram of Simulated Means\",\n       x = \"Simulated Mean Price\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](lab_9_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nThe red line represents the observed statistic of 17140 dollars. Notice that the observed statistic is located in the left tail of the null distribution, which is consistent with our alternative hypothesis that the average sale price is less than 20,000 dollars.\nTo find the P-value, we need to calculate the proportion of simulated means that are as extreme as or more extreme than the observed statistic (17140 dollars) in the direction specified by the alternative hypothesis (less than).\nWe can achieve this easily the `get_p_value()` function from the `infer` package. See code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_distribution |>\n  get_p_value(obs_stat = 17140, direction = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1   0.193\n```\n\n\n:::\n:::\n\n\n\n\n### [Interpretation & Conclusion]{style=\"color:#4166f5;\"}\n\nThe p-value is 0.193 (about 19.3%). This represents the likelihood of obtaining an average mean of 17,400 or less assuming that the null hypothesis were true. \nSince the p-value is greater than the discernibility level of 0.05 (5%), we **fail to reject** the null hypothesis. Our data does not provide enough evidence to suggest that the average sale price at the franchise is different (less than) 20,000 dollars.\n\n### [Confidence Interval]{style=\"color:#4166f5;\"}\n\nNext, we want to create a confidence interval to approximate the range within which we expect to find the true average sale price. We first run several bootstrap samples from the original sample as shown below. Study this code and note how it differs from the one used for hypothesis testing above.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) # Prevents simulated data from changing.\nbootstrap_dist <- sales_data |>\n  specify(response = price) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"mean\")\n```\n:::\n\n\n\n\nWe can visualize the bootstrap distribution using a histogram. This step is often optional but it can be a good way to verify that your interval is centered around the observed statistic:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_dist |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(binwidth = 1400, fill = \"#4963D4\", color = \"white\") +\nlabs(title = \"Histogram of Bootstrap Means\",\n       x = \"Simulated Bootstrap Mean Price\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](lab_9_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\nNotice that the histogram is centered around the observed statistic of \\$17,140 pounds. Recall that the null distribution was centered around the null value of \\$20,000. The bootstrap distribution is used to create confidence intervals while the null distribution is used for hypothesis testing.\n\nNext, we can use the `get_ci()` function to find the lower and the upper boundaries of the 95% confidence interval as shown below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_dist |>\n  get_ci(level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    11780    22860\n```\n\n\n:::\n:::\n\n\n\n\nThe 95% confidence interval is approximately (\\$11,780, \\$22,860). This means that we are 95% confident that the true average sale price is between \\$11,780 and \\$22,860. This interval includes the null value (\\$20,000), meaning \\$20,000 is a plausible value. This further supports the conclusion reached under the hypothesis testing part.\n\n## [Exercises]{style=\"color:#4166f5;\"}\n\nThere are no questions to answer. Render your quarto document and submit the PDF to Canvas under Lab 9.\n\n\n",
    "supporting": [
      "lab_9_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}