{
  "hash": "21f88596de7e15a239c3f64840804634",
  "result": {
    "engine": "knitr",
    "markdown": "---\ncategories: \"Lab 8\"\ntitle: \"Lab 8: Inference for a Single Proportion\"\nexecute:\n  eval: true\nformat:\n  html: \n    code-link: true #Supposed to create a link to documentation but its not, for some reason.\n    code-block-border-left: \"#31BAE9\"\n    code-fold: show #also try true OR false and decide if you like it.\n    code-tools: false\n    code-copy: true\n---\n\n\n\n\n\n\n## [Introduction]{style=\"color:#4166f5;\"}\n\nIn the previous lab (lab 7), we created a confidence interval for a single proportion using the `infer` package. In this lab, we will perform a hypothesis test for a single proportion and also create a confidence interval and compare the results.\n\n## [Context & Scenario]{style=\"color:#4166f5;\"}\n\nThe Development, Relief, and Education for Alien Minors Act (DREAM Act) is a legislative proposal in the United States that aims to provide a pathway to legal status for undocumented people who were brought to the U.S. as children. These people are often referred to as DREAMERS. The DREAM Act passed the House of Representatives in 2010 but failed to reach the 60-vote requirement in the Senate. The Act has been a topic of heated debate in U.S. politics for many years.\n\nA Gallup Poll conducted in 2010, reported that about 54% of Americans supported the DREAM act ([Migration Policy Institute, 2010](https://www.migrationpolicy.org/article/dream-act-passes-house-during-lame-duck-session-faces-uphill-battle-senate?utm_source=chatgpt.com)). The poll also found that the opinions on the DREAM Act vary by political leaning.\n\n## [Research Question and Hypotheses]{style=\"color:#4166f5;\"}\n\nWe want to use statistical inference (hypothesis test and a confidence interval) to answer the research question:\n\n***Research Question:*** Is the proportion of Americans who supported the DREAM Act in 2012 different from 0.54 (or 54%).\n\n***Null Hypothesis:*** The proportion of Americans who supported the DREAM Act in 2012 is equal to 0.54.\n\n$$H_0: p = 0.54.$$\n\n***Alternative Hypothesis:*** The proportion of Americans who supported the DREAM Act in 2012 is different from 0.54.\n\n$$H_0: p \\neq 0.54.$$\n\n## [Creating your quarto file]{style=\"color:#4166f5;\"}\n\nCreate a new quarto document with the title **Inference for a Single Proportion** and save the file as `lab_8_Explo`. Please check previous labs (e.g., [lab 4](https://jmochogi.github.io/business-stats-f25/labs/lab_4.html#creating-a-quarto-file)) if you are unsure how to do this. Be sure to delete all the default text in the new file before you start the lab exploration.\n\n## [Packages and Data]{style=\"color:#4166f5;\"}\n\nThe dataset we will use is called `dream` and is available in the openintro `package`. We will also use the `infer` and `tidyverse` packages. Use the following code to load the packages and the data:\n\n``` toml\nlibrary(openintro)\nlibrary(tidyverse)\nlibrary(infer)\ndata(dream)\n```\n\nAfter running the code chunk, the `dream` dataset should appear in the environment area. Open it and examine the cases and variables. be available for use in your analysis. You can run the code chunk below to view the first few rows of the dataset:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dream)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  ideology     stance\n  <fct>        <fct> \n1 Conservative Yes   \n2 Conservative Yes   \n3 Conservative Yes   \n4 Conservative Yes   \n5 Conservative Yes   \n6 Conservative Yes   \n```\n\n\n:::\n:::\n\n\n\n\nThere are two variables in this dataset - ideology (conservative, liberal, moderate) and stance (Yes, No, Note sure). Since we are interested in a single proportion (proportion of Americans who supported the DREAM Act), we will focus on the `stance` variable only.\n\n## [The Observed Statistic]{style=\"color:#4166f5;\"}\n\nNotice that the `stance` variable has 3 levels - Yes, No, Not sure. In order to run inference for a single proportion, we need the `stance` variable to have only two levels. To do this, we can group `No` and `Not sure` together and call them `Not Yes`. See the code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndream_filtered <- dream |>\n  mutate(stance = if_else(stance == \"Yes\", \"Yes\", \"Not Yes\"))\n```\n:::\n\n\n\n\nThen, we create the summary table again using the filtered dataset:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndream_filtered |>\n  group_by(stance) |>\n  summarize(count = n()) |>\n  mutate(proportion = count / sum(count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  stance  count proportion\n  <chr>   <int>      <dbl>\n1 Not Yes   436      0.479\n2 Yes       474      0.521\n```\n\n\n:::\n:::\n\n\n\n\nThus, the observed statistic is 0.521 (or 52.1%). This is the proportion of Americans ***in the sample*** that supported the DREAM Act in 2012.\n\n## [Running Simulations]{style=\"color:#4166f5;\"}\n\nNext, we want to run simulations to see the distribution of the observed statistic under the null hypothesis. We will use the `infer` package to do this. Run the code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) # Prevents simulated data from changing.\ndream_sim <- dream_filtered |>\n  specify(response = stance, success = \"Yes\") |>\n  hypothesize(null = \"point\", p = 0.54) |>\n  generate(reps = 500, type = \"draw\") |>\n  calculate(stat = \"prop\")\n```\n:::\n\n\n\n\nThe code should run without errors. The `dream_sim` object (see environment) contains 500 simulated proportions under the null hypothesis.\n\n## [Visualizing the Null Distribution]{style=\"color:#4166f5;\"}\n\nWe can visualize the null distribution of the proportions using a histogram. We also indicate the location of observed statistic. See code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndream_sim |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(bins=45)+\n  geom_vline(xintercept = 0.521, color = \"red\", linetype = \"dashed\") \n```\n\n::: {.cell-output-display}\n![](lab_8-Single-Prop_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\nNote that the center of the ***null distribution*** is around 0.54, which is expected since that is the value we specified in the null hypothesis. The observed statistic appears to be close to the null value (0.54).\n\n## [Calculating the P-value]{style=\"color:#4166f5;\"}\n\nThe P-value is the fraction of values at or more extreme than the observed statistic in the null distribution. Since we are doing a two-tailed test, we need to consider both tails of the distribution. We can use the `get_p_value()` function from the `infer` package to calculate the P-value as shown below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value <- dream_sim |>\n  get_p_value(obs_stat = 0.521, direction = \"two-sided\")\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1    0.22\n```\n\n\n:::\n:::\n\n\n\n\n## [Interpretation & Conclusion]{style=\"color:#4166f5;\"}\n\nThe P-value we obtained is approximately 0.22 (or 22%). Based on the 5% discenibility level, we do not have enough evidence to reject the null hypothesis. Therefore, we conclude that there is not enough evidence to suggest that the proportion of Americans that supported the DREAM Act in 2012 is different from 54%.\n\n## [Confidence Interval]{style=\"color:#4166f5;\"}\n\nTo create a 95% confidence interval, we use our filtered data to run bootstrap simulations to create several bootstrap samples:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12) # Prevents simulated data from changing.\ndream_boot <- dream_filtered |>\n  specify(response = stance, success = \"Yes\") |>\n  generate(reps = 500, type = \"bootstrap\") |>\n  calculate(stat = \"prop\")\n```\n:::\n\n\n\n\nWe can visualize the bootstrap distribution using a histogram:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndream_boot |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(bins=55)\n```\n\n::: {.cell-output-display}\n![](lab_8-Single-Prop_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\nNotice that the bootstrap distribution is centered around the ***observed statistic*** (approx. 0.52). Next, we can use the `get_ci()` function to create a 95% confidence interval as shown below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndream_boot |>\n  get_ci(level = 0.95, type = \"percentile\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    0.488    0.552\n```\n\n\n:::\n:::\n\n\n\n\nThe 95% confidence interval is approximately (0.488 to 0.552) or 48.8% to 55.2%. This means that we are 95% confident that the true proportion of Americans who supported the DREAM Act in 2012 is between 48.8% and 55.2%. This interval further supports the conclusion reached for the hypothesis test since the value of 54% falls inside this confidence interval.\n\n## [Exercises]{style=\"color:#4166f5;\"}\n\nIn this lab exercises, you will use the same dataset (`dream`) used in the exploration above. <br> Create a new quarto file and title it **Inference for a Single proportion**. Save the document as **Lab_8_Exe**. Load the following packages:\n\n``` toml\n#| include: false\nlibrary(openintro)\nlibrary(tidyverse)\nlibrary(infer)\ndata(dream)\n```\n\n***Scenario:*** A [Gallup poll](https://news.gallup.com/poll/388988/political-ideology-steady-conservatives-moderates-tie.aspx) conducted in 2010 indicated that 35% of Americans identified as **Moderate** when it comes to political ideology. The goal is for you to use the `dream` dataset (collected in 2012) and statistical inference ideas to examine whether the proportion of Americans who identified as `Moderate` in 2012 was different from 0.35 (35%).\n\n1.  **(2 pts)** What does the variable `ideology` in the `dream` dataset represent? What are the levels of this variable?\n\n2.  **(2 pts)** State the null and alternative hypotheses to test whether the proportion of Americans who identified as `Moderate` in 2012 is different from 0.35 (or 35%).\n\n3.  **(4 pts)** What would be the ***observed statistic*** in this scenario? Compute it. <br> (**Hint:** You may want to modify the variable `ideology` so that it has two levels only)).\n\n4.  **(4 pts)** Run 1000 simulations to create the null distribution. Visualize this distribution using a histogram and indicate the location of the ***observed statistic***. Why is this distribution centered around 0.35?\n\n5.  **(4 pts)** Use the `get_p_value()` function to find the P-value, then write the conclusion of your hypothesis test in context of the data.\n\n6.  **(4 pts)** Create a 95% confidence interval for the proportion of Americans who identified as `moderate` in 2012. Write the interpretation of this interval in context of the data and indicate whether your conclusion from the hypothesis test is supported by this interval.\n\n\n\n\n````{=html}\n<!-- Answers to Exercises \n\n::: {.cell}\n\n```{.r .cell-code}\nnew_dream <- dream|>\n  mutate(ideology=ifelse(ideology==\"Moderate\", \"Moderate\", \"Not Moderate\"))\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_dream |>\n  group_by(ideology) |>\n  summarize(count = n()) |>\n  mutate(proportion = count / sum(count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  ideology     count proportion\n  <chr>        <int>      <dbl>\n1 Moderate       363      0.399\n2 Not Moderate   547      0.601\n```\n\n\n:::\n:::\n\nHyp. Test:\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulated_diffs <- new_dream|>\n  specify(response=ideology, success=\"Moderate\")|>\n  hypothesise(null = \"point\", p=.35)|>\n  generate(reps=1000, type=\"draw\")|>\n  calculate(stat=\"prop\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulated_diffs |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(bins=55)+\n  geom_vline(xintercept = 0.3989011, color = \"red\", linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](lab_8-Single-Prop_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nCalculate proportions from the new_dream dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulated_diffs|>\n  get_p_value(obs_stat = 0.3989011, direction = \"two-sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1   0.004\n```\n\n\n:::\n:::\n\n\n\nBootstrap CI:\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulated_bootstrap<- new_dream|>\n  specify(response = ideology, success = \"Moderate\") |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"prop\")\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulated_bootstrap |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(bins=55)\n```\n\n::: {.cell-output-display}\n![](lab_8-Single-Prop_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nget_ci(simulated_bootstrap, level = 0.95, type = \"percentile\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    0.368    0.433\n```\n\n\n:::\n:::\n-->\n````\n",
    "supporting": [
      "lab_8-Single-Prop_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}