{
  "hash": "8d9d9889796b19b061081a6643a47c99",
  "result": {
    "engine": "knitr",
    "markdown": "---\ncategories: \"Lab 6\"\ntitle: \"Lab 6: Introduction to Inference - Confidence Intervals\"\nexecute:\n  eval: true\nformat:\n  html: \n    code-link: true #Supposed to create a link to documentation but its not, for some reason.\n    code-block-border-left: \"#31BAE9\"\n    code-fold: show #also try true OR false and decide if you like it.\n    code-tools: false\n    code-copy: true\n---\n\n\n\n\n\n## [Introduction]{style=\"color:#4166f5;\"}\n\nIn the previous lab (lab 4), we ran a hypothesis test for difference in two proportions via a simulation process known as randomization. The goal was to test ***whether or not*** the data provide evidence that female candidates were discriminated against in promotion decisions. We generated 1000 differences and found a small P-value which led to the conclusion that discrimination was likely going on (in the population).\n\nIn this lab, we will create a confidence interval for the same scenario used in lab 4. Unlike a hypothesis test, a confidence interval estimates the ***\"magnitude of the discrimination\"*** by providing a range of values within which we may expect the true population parameter (in this case difference in promotion proportions) to be. We will do this using a simulation process known as ***bootstrapping***.\n\n## [Creating a quarto file]{style=\"color:#4166f5;\"}\n\nGo to posit cloud (<https://posit.cloud>) and open the MATH 144 project. Once your MATH 144 project is open, clean up the console and the environment. Close any open documents and data sets that you don't need.\n\nNext, create your new quarto file as follows:\n\n- File \\> New File \\> Quarto document. Use the file name `Lab_6`. Do not delete the `.qmd` extension.\n\n- Add the `author` and `title` keys to the `YAML` section. Write your name (in quotes) in the author field and set the title to `Introduction to Statistical Inference - Confidence Intervals`.\n\n- Change the output option to `pdf` then click on `render`. A PDF document with your name and title should pop up. If the popup blocker shows up, click try again.\n\n## [Packages and Data]{style=\"color:#4166f5;\"}\n\nThis lab needs the same libraries as the previous one:\n\n``` toml\nlibrary(openintro)\nlibrary(tidyverse)\nlibrary(infer)\ndata(sex_discrimination)\n```\n\nAfter running the code chunk, the `sex_discrimination` data set will be available for use. You can click on the data set in the environment area to view it.\n\n## [The Observed Statistic]{style=\"color:#4166f5;\"}\n\nRecall from lab 4, that the observed statistic was 0.2917, meaning the difference in promotion rates between males and females **in the sample** was about 29.2%.\n\n## [Bootstrap Simulations]{style=\"color:#4166f5;\"}\n\nWe want to run a simulation process known as bootstrapping to create a confidence interval for the true population parameter (the true difference in promotion rates between the sexes in the population).\n\nExamine and run the code below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) #This prevents simulated data from changing.\nbootstrap_diffs <- sex_discrimination |>\n  specify(decision~sex, success = \"promoted\") |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"diff in props\", order=c(\"male\",\"female\"))\n```\n:::\n\n\n\n**Question:** What differences do you notice in the code above compared to the randomization code from lab 4?\n\n## [Visualizing the Bootstrap Distribution]{style=\"color:#4166f5;\"}\n\nWe can visualize the bootstrap distribution of the proportions using a histogram. See code below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_diffs |>\n  ggplot(aes(x = stat)) +\n  geom_histogram(binwidth = 0.05, fill = \"#4963D4\", color = \"white\") +\n  labs(title = \"Bootstrap Distribution of Differences\",\n       x = \"Simulated Differences in Proportions\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](lab_7_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\nThe histogram above shows the distribution of the simulated difference in proportions. This distribution gives us an idea of the variability of the observed statistic. The 95% confidence interval will be constructed using this distribution, which will provide a range of plausible values for the true difference in promotion rates.\n\n## [Constructing the Confidence Interval]{style=\"color:#4166f5;\"}\n\nTo find the 95% confidence interval for the proportion of small cars, we use the `get_ci()` function from the `infer` package. A 95% confidence interval means that we need 95% of the simulated data in the middle. This means that each tail (right and left) shares 2.5%. Therefore, the interval runs from 2.5th percentile and the 97.5th percentile. The get_ci() function from the `infer` package is used for this as shown below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_diffs |>\n  get_ci(level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1   0.0490    0.522\n```\n\n\n:::\n:::\n\n\n\nThe output above shows the lower (2.5th percentile) and upper (97.5th percentile) bounds of the 95% confidence interval.\n\n## [Interpretation & Conclusion]{style=\"color:#4166f5;\"}\n\nWe can interpret the interval as follows: We are 95% confident that the true difference in proportion of promotions between male and female candidates lies between 0.049 (4.9%) and 0.522 (52.2%). This means that the true difference in promotion rates could be as low as 4.9% or as high as 52.2%, but it is unlikely to be outside of this range. Since the interval does not contain 0, we can conclude that there is likely a significant difference in promotion. This interval further supports the conclusion from lab 6 that there is likely discrimination against female candidates in the promotion decisions at the company.\n\n## [Exercises]{style=\"color:#4166f5;\"}\n\nOne-hundred and fifty students were recruited in a study that aimed to understand whether reminding college students about saving money for later would make them more thriftier. The students were split into 2 equal groups (control and experiment). Each student was given the following prompt:\n\n*\"Imagine that you have been saving some extra money on the side to make some purchases, and on your most recent visit to the video store you come across a special sale on a new video. This video is one with your favorite actor or actress, and your favorite type of movie (such as a comedy, drama, thriller, etc.). This particular video that you are considering is one you have been thinking about buying for a long time. It is available for a special sale price of \\$14.99. What would you do in this situation? Buy video or Not buy video?\"*\n\nStudents in the control group were given the following two options:\n\nA.  Buy video\nB.  Not buy video\n\nStudents in the experiment group were given a slightly modified option B:\n\nA.  Buy video\nB.  Not buy this video. *Keep the \\$14.99 for other purchases*.\n\nThe goal is to use the ideas learned in the above explorations to create the relevant confidence interval and interpret it in context.\n\n1.  ***(4 pts)*** Generate 500 bootstrap differences that can be used to create the relevant confidence interval. Be sure to use the `infer` package functions (`specify()`, `generate()`, and `calculate()`) as illustrated above and save this data as **bootstrap_diffs**.\n2.  ***(2 pts)*** Create a histogram to visualize the distribution of the bootstrap differences generated in #1 above. Describe any patterns apparent in the histogram making sure to state its approximate center and the reason for the location of the center.\n3.  ***(2 pts)*** Use the `get_ci()` function to create the relevant 95% confidence interval.\n4.  ***(2 pts)*** Interpret the confidence interval in context. Does the confidence interval support the conclusion reached under hypothesis testing in lab 6? Explain.\n",
    "supporting": [
      "lab_7_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}